### ISSUE TITLE
Add OP-Erigon

### ISSUE THREAD

**Issue by barnabasbusa** [ethpandaops/optimism-package#12]
https://github.com/testinprod-io/op-erigon

**Comment by mininny** [comment]
Hi @barnabasbusa , 

I created a draft PR here for adding op-erigon to the package. https://github.com/ethpandaops/optimism-package/pull/30
I reused most of the configuration from op-geth and op-reth, but haven't really verified the implementation yet. 

Is there any CI running for the repo, or are there any ways that I can test whether this works? Thanks 😄

**Comment by barnabasbusa** [comment]
Hey thanks for the PR, I'll add some basic docs how to get it running locally. Would be cool to add some op-erigon specific ci tests in .github/tests/

**Comment by mininny** [comment]
Sounds great, please let me know when the docs are ready! 
Also, are there any existing tests for op-geth/op-reth that I can refer to, or should I add a new ci test pipeline?

**Comment by barnabasbusa** [comment]
please just create a new one for op erigon specifically.

Some basic docs: https://github.com/ethpandaops/optimism-package/issues/31
