### ISSUE TITLE
how can I use L1 wallet address or how can I get test eth coin in devnet work?

### ISSUE THREAD

**Issue by zhouop0** [ethpandaops/optimism-package#52]
optimism_package:
  participants:
    - el_type: op-geth
      cl_type: op-node
ethereum_package:
  participants:
    - el_type: geth
  network_params:
    preset: minimal
  additional_services:
    - dora
    - blockscout

I use above yaml file to launch the network. Now, I need to invoke L1 contract method, but I have not test eth. How can I use address which is inited in genesis.json or other way?

I use command (eth.accounts) in geth console, and eth.accounts is empty.

**Comment by barnabasbusa** [comment]
By default this mnemonic will be prefunded: https://github.com/ethpandaops/ethereum-package/blob/main/network_params.yaml#L63-L66
