### ISSUE TITLE
Deploying L2 contracts is super slow and makes for bad devex

### ISSUE THREAD

**Issue by samlaf** [ethpandaops/optimism-package#68]
I've been playing around with the devnet trying to add features to it, but the L2 deployment step is super slow and makes for a pretty bad dev experience (https://xkcd.com/303/)

![image](https://github.com/user-attachments/assets/92054e7b-f3e2-4a08-b2a1-48a2ae42c559)

Not super sure what the culprit is here. I noticed that the docker-compose devnet uses [`op-node genesis l1`](https://github.com/ethereum-optimism/optimism/blob/2272a5dea9e2b4bdb7c78903a1ce00a0ea8cb003/bedrock-devnet/devnet/__init__.py#L194) to prepare an L1 genesis file, but the kurtosis devnet does not. But that probably under the hood just deploys the contracts using forge and then builds the genesis file...?

Otherwise would it just be the fact that the deployment is done inside a docker container as opposed to using forge subcommand execution? I have noticed in the past that forge deploys from within a docker container were much much slower than using native forge, but I'm unsure why.

Any other reasons that could explain the discrepancy?

**Comment by mslipper** [comment]
Hey Sam!

I'm working on some improvements to the deployment setup which should make things faster. The Kurtosis package wraps some poorly maintained OP Labs Docker images, and I'll be replacing them with a more modular and performant setup.

**Comment by samlaf** [comment]
Awesome looking forward!
