### ISSUE TITLE
Misconfigured sequencer forwarding

### ISSUE THREAD

**Issue by klkvr** [ethpandaops/optimism-package#86]
Right now for all execution clients sequencer URL for forwarding is configured as `sequencer_context.beacon_http_url` where `sequencer_context` is sequencer's CL context, thus `beacon_http_url` is sequencer's consensus client RPC:
https://github.com/ethpandaops/optimism-package/blob/05d0fe972f8096570432f8360902430e0490d619/src/el/op-geth/op_geth_launcher.star#L213

Is this intended? In Reth, if this parameter is configured, we forward `sendRawTransaction` requests directly. I believe that those can't be handled by op-node, so I'd expect this to be configured with sequencer's EL RPC?

**Comment by tynes** [comment]
This should definitely be pointing to the sequencer's EL client
